baseURL = 'https://eraydiler.github.io/'
languageCode = 'en-us'
title = "I'm so glad you're here 👋🏼"
theme = 'hello-friend-ng'
pagerSize     = 10

copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Let's make this a better world!"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  author = "Eray Diler"
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

defaultContentLanguage = "en"

[params.logo]
  logoText = "git checkout main"
  logoHomeLink = "/"

[[menu.main]]
    identifier = "about"
    name       = "about"
    url        = "/me/about"

[[menu.main]]
    identifier = "posts"
    name       = "posts"
    url        = "/posts"

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #  
  # Addon: Social icons
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #

  [[params.social]]
    name = "email"
    url  = "mailto:eray.diler@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/eraydiler"

  [[params.social]]
    name = "stackoverflow"
    url  = "https://stackoverflow.com/users/14178169/eray-diler"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/eray-diler/"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/eray_diler"

  # Custom footer 
  # If you want, you can easily override the default footer with your own content. 
  #
  [params.footer]
    trademark = 2024
    rss = true
    copyright = true
#    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Made with &#10084; by <a href=\"https://github.com/eraydiler\">Eray Diler</a>"
    ]
