baseURL = 'https://eraydiler.github.io/'
languageCode = 'en-us'
title = "I'm so glad you're here 👋🏼"
theme = 'hello-friend-ng'
pagerSize     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Let's make this a better world!"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

defaultContentLanguage = "en"

[params.logo]
  logoText = "git checkout main"
  logoHomeLink = "/"

[[menu.main]]
    identifier = "blog"
    name       = "blog"
    url        = "/posts"